### ISSUE TITLE
Workflow "Azure BlobStore Integration / Azure online" consistently fails

### ISSUE THREAD

**Issue by jodygarnett** [GeoWebCache/geowebcache#1321]
Several recent PRs are all failing in the same spot:

> HTTP request failed with status code:'403'

Examples:

* https://github.com/GeoWebCache/geowebcache/pull/1319
* https://github.com/GeoWebCache/geowebcache/pull/1320

As shown here https://github.com/GeoWebCache/geowebcache/actions/workflows/azure-integration.yml

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/ab1a05f0-fe4c-4e6b-b545-8d6eca139b8e">

Ideas?

**Comment by jodygarnett** [comment]
@groldan  please advise?

**Comment by jodygarnett** [comment]
@groldan responded that it was safe to ignore this workflow failure

**Comment by petersmythe** [comment]
> @groldan responded that it was safe to ignore this workflow failure

https://github.com/GeoWebCache/geowebcache/pull/1316#issuecomment-2346581058

**Comment by groldan** [comment]
Closing as fixed after upgrading the azure credentials
