### ISSUE TITLE
Wrong character encoding in GetCapabilities

### ISSUE THREAD

**Issue by flansch** [GeoWebCache/geowebcache#166]
I'm using the GeoWebCache integrated into GeoServer 2.2. When accessing the GetCapabilities document of the GeoWebCache WMS service, german umlauts in the returned document are encoded in ISO-8859-1 encoding while it should be UTF-8 according to the xml declaration:

<?xml version="1.0" encoding="UTF-8"?>

If accessing GetCapabilities of GeoServer directly, the characters are encoded correctly. 

For example, for the letter ä inside the word Amtsgebäude the hex character code E4 is returned while it should be C3 A4.

GeoWebCache:
![getcap_encoding_gwc](https://f.cloud.github.com/assets/3717998/201637/5102bd5e-80f9-11e2-8ce9-a8fb0728aad4.png)

GeoServer:
![getcap_encoding_geoserver](https://f.cloud.github.com/assets/3717998/201636/509d7f98-80f9-11e2-936b-9c247a097ba2.png)

**Comment by anderserla** [comment]
Were having the same problems in Geoserver 2.5. 
Does anyone have any plans on fixing this issue, or could anyone give a hint on how to fix it?

**Comment by smithkm** [comment]
Should have been fixed in GeoWebCache 1.6 https://github.com/GeoWebCache/geowebcache/commit/abfbfd944bb1d445acaee3daae1c88211f3bcdc3
