### ISSUE TITLE
Request with WMS 1.3.0 - doesn't accept EPSG

### ISSUE THREAD

**Issue by jonathan-wcc** [GeoWebCache/geowebcache#168]
I suspect GeoWebCache doesn't support WMS 1.3.0 (the documentation doesn't seem to explicitly say that, though it does say it was designed for 1.1.0).
When I make a request with 1.3.0, I get this in my headers:

geowebcache-miss-reason	exception occurred: NumberFormatException: For input string: "x-ogc:def:crs:EPSG:27700"

**Comment by smithkm** [comment]
This is really more of a question for the mailing list. GitHub tickets are for specific bugs or feature requests we've narrowed down enough to understand what needs to be fixed.
