### ISSUE TITLE
GetCapabilities Ignores version attribute

### ISSUE THREAD

**Issue by jonathan-wcc** [GeoWebCache/geowebcache#169]
Using GeoServer 2.3 RC1, and "GeoWebCache version 1.4-SNAPSHOT, build 83b284b341ef25fe89adf2eb7858991defa64e57/83b284b341ef25fe89adf2eb7858991defa64e57"

The "WMS 1.1.1 GetCapabilities document" link works fine, but if I alter the URL to version=1.3.0 or version=1.0.0, the exact same GetCapabilities document is returned.

Shouldn't it return something else, Even if those two WMS versions are unsupported?

**Comment by smithkm** [comment]
It sounds like this is an issue you should bring up on the GeoServer users list, assuming it hasn't been fixed already.
