### ISSUE TITLE
layer title same as layer name in capabilities doc (for layer group)

### ISSUE THREAD

**Issue by fgravin** [GeoWebCache/geowebcache#197]
In the response of a getCapabilities (embeded GWC in GS 2.3.2), the tag title of the layer is a copy of the tag name **for layer groups**. Even though the title has been specified in the layer definition.

- GWC getCapabilities:

          <Layer queryable="1">
          <Name>cigal:CIGAL_ORTHORVB_2011_2012_ALSACE_CC48</Name>
          <Title>cigal:CIGAL_ORTHORVB_2011_2012_ALSACE_CC48</Title>
          </Layer>

- WMS getCapabilities

          <Layer queryable="1">
          <Name>cigal:CIGAL_ORTHORVB_2011_2012_ALSACE_CC48</Name>
          <Title>CIGAL ORTHO RVB 2011 2012</Title>

**Comment by smithkm** [comment]
This should be reported as a GeoServer issue.
