### ISSUE TITLE
BUG - WMS capabilities has wrong coors inside <BoundingBox> tag

### ISSUE THREAD

**Issue by OtakarRuzicka** [GeoWebCache/geowebcache#210]
Hello,
during tuning my WMS and WMST services I found (probably) bugs.
1/ WMS capabilities has wrong coors inside &lt;BoundingBox&gt; tag.
2/ Using tag &lt;zoomStart&gt; in &lt;gridSubset&gt; is leading into crash WMS.

I also noticed that setting &lt;zoomStart&gt; repairs coors inside &lt;BoundingBox&gt;.

Here is part of my GWC config:
(geowebcache.xml)
...
&lt;wmsLayer&gt;
	&lt;name&gt;oleata_dmu100&lt;/name&gt;
	&lt;enabled&gt;true&lt;/enabled&gt;
	&lt;metaInformation&gt;
		&lt;title&gt;Oleata&lt;/title&gt;
		&lt;description&gt;Vizualizace DMU100 pro LMS.&lt;/description&gt;
	&lt;/metaInformation&gt;
	&lt;mimeFormats&gt;
		&lt;string&gt;image/png&lt;/string&gt;
	&lt;/mimeFormats&gt;
	&lt;gridSubsets&gt;
		&lt;gridSubset&gt;
			&lt;gridSetName&gt;EPSG:3857&lt;/gridSetName&gt;
			&lt;extent&gt;
				&lt;coords&gt;
					&lt;double&gt;1324000.0&lt;/double&gt;
					&lt;double&gt;6151200.0&lt;/double&gt;
					&lt;double&gt;2133600.0&lt;/double&gt;
					&lt;double&gt;6681300.0&lt;/double&gt;
				&lt;/coords&gt;
			&lt;/extent&gt;
			&lt;zoomStop&gt;15&lt;/zoomStop&gt;
			&lt;minCachedLevel&gt;12&lt;/minCachedLevel&gt;
			&lt;maxCachedLevel&gt;15&lt;/maxCachedLevel&gt;
		&lt;/gridSubset&gt;
	&lt;/gridSubsets&gt;
	&lt;expireCacheList&gt;
		&lt;expirationRule minZoom="0" expiration="-2" /&gt;
	&lt;/expireCacheList&gt;
	&lt;expireClientsList&gt;
		&lt;expirationRule minZoom="0" expiration="-2" /&gt;
	&lt;/expireClientsList&gt;
	&lt;wmsUrl&gt;
		&lt;string&gt;http://192.168.232.33/mapsrv6/service&lt;/string&gt;
	&lt;/wmsUrl&gt;
	&lt;vendorParameters&gt;map=/ms4w/apache/htdocs/services/dmu_100/dmu100.map&lt;/vendorParameters&gt;
	&lt;wmsLayers&gt;oleata&lt;/wmsLayers&gt;
	&lt;wmsStyles&gt;default&lt;/wmsStyles&gt;
	&lt;transparent&gt;true&lt;/transparent&gt;
	&lt;metaWidthHeight&gt;&lt;int&gt;4&lt;/int&gt;&lt;int&gt;4&lt;/int&gt;&lt;/metaWidthHeight&gt;
	&lt;wmsVersion&gt;1.1.0&lt;/wmsVersion&gt;
	&lt;gutter&gt;0&lt;/gutter&gt;
&lt;/wmsLayer&gt;
...

Both WMS(tiled/untiled) and WMTS are running. BUT, if client receives WMS capabilities, there are wrong coors in &lt;BoundingBox&gt;.

--------- CAPABILITIES ---------

wms-getcapabilities.xml
&lt;WMT_MS_Capabilities version="1.1.1"&gt;
...
&lt;Capability&gt;
...
&lt;VendorSpecificCapabilities&gt;
    &lt;TileSet&gt;
      &lt;SRS&gt;EPSG:3857&lt;/SRS&gt;
      &lt;BoundingBox SRS="EPSG:3857" minx="0.0" miny="5009377.085000001"  maxx="2504688.5425000004"  maxy="7514065.627500001" /&gt;
      &lt;Resolutions&gt;156543.03390625 78271.516953125 39135.7584765625 19567.87923828125 9783.939619140625 4891.9698095703125 2445.9849047851562 1222.9924523925781 611.4962261962891 305.74811309814453 152.87405654907226 76.43702827453613 38.218514137268066 19.109257068634033 9.554628534317017 4.777314267158508 &lt;/Resolutions&gt;
      &lt;Width&gt;256&lt;/Width&gt;
      &lt;Height&gt;256&lt;/Height&gt;
      &lt;Format&gt;image/png&lt;/Format&gt;
      &lt;Layers&gt;oleata_dmu100&lt;/Layers&gt;
      &lt;Styles&gt;&lt;/Styles&gt;
    &lt;/TileSet&gt;
&lt;/VendorSpecificCapabilities&gt;
...
&lt;Layer&gt;
	&lt;Title&gt;GeoWebCache WMS&lt;/Title&gt;
	&lt;Abstract&gt;Note that not all GeoWebCache instances provide a full WMS service.&lt;/Abstract&gt;
	&lt;LatLonBoundingBox minx="-180.0" miny="-90.0" maxx="180.0" maxy="90.0"/&gt;
&lt;Layer&gt;
	&lt;Name&gt;oleata_dmu100&lt;/Name&gt;
	&lt;Title&gt;Oleata&lt;/Title&gt;
	&lt;Abstract&gt;Vizualizace DMU100 pro LMS.&lt;/Abstract&gt;
	&lt;SRS&gt;EPSG:3857&lt;/SRS&gt;
	&lt;BoundingBox SRS="EPSG:3857" minx="0.0" miny="5009377.085000001" maxx="2504688.5425000004" maxy="7514065.627500001"/&gt;
&lt;/Layer&gt;
&lt;/Capability&gt;
&lt;/WMT_MS_Capabilities&gt;

wmts-getcapabilities
&lt;Contents&gt;
  &lt;Layer&gt;
    &lt;ows:Title&gt;Oleata&lt;/ows:Title&gt;
    &lt;ows:Abstract&gt;Vizualizace DMU100 pro LMS.&lt;/ows:Abstract&gt;
    &lt;ows:Identifier&gt;oleata_dmu100&lt;/ows:Identifier&gt;
    &lt;Style isDefault="true"&gt;
      &lt;ows:Identifier&gt;default&lt;/ows:Identifier&gt;
    &lt;/Style&gt;
    &lt;Format&gt;image/png&lt;/Format&gt;
    &lt;TileMatrixSetLink&gt;      &lt;TileMatrixSet&gt;EPSG:3857&lt;/TileMatrixSet&gt;
      &lt;TileMatrixSetLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:0&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;0&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;0&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;0&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;0&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:1&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;0&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;0&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;1&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;1&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:2&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;1&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;1&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;2&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;2&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:3&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;2&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;2&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;4&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;4&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:4&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;5&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;5&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;8&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;8&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:5&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;10&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;11&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;17&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;17&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:6&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;21&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;22&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;34&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;35&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:7&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;42&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;44&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;68&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;70&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:8&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;85&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;88&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;136&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;141&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:9&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;170&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;177&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;272&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;283&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:10&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;341&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;354&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;545&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;566&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:11&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;682&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;709&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;1091&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;1133&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:12&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;1365&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;1419&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;2183&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;2266&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:13&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;2730&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;2838&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;4366&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;4532&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:14&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;5460&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;5677&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;8733&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;9064&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:15&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;10920&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;11354&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;17466&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;18128&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
      &lt;/TileMatrixSetLimits&gt;
    &lt;/TileMatrixSetLink&gt;  &lt;/Layer&gt;
&lt;/Contents&gt;

--------- INSERTING  &lt;zoomStart&gt; ---------
I inserted &lt;zoomStart&gt; into &lt;gridSubset&gt;:
&lt;gridSubset&gt;
	&lt;gridSetName&gt;EPSG:3857&lt;/gridSetName&gt;
	&lt;extent&gt;
		&lt;coords&gt;
			&lt;double&gt;1324000.0&lt;/double&gt;
			&lt;double&gt;6151200.0&lt;/double&gt;
			&lt;double&gt;2133600.0&lt;/double&gt;
			&lt;double&gt;6681300.0&lt;/double&gt;
		&lt;/coords&gt;
	&lt;/extent&gt;
	&lt;zoomStart&gt;11&lt;/zoomStart&gt;
	&lt;zoomStop&gt;15&lt;/zoomStop&gt;
	&lt;minCachedLevel&gt;12&lt;/minCachedLevel&gt;
	&lt;maxCachedLevel&gt;15&lt;/maxCachedLevel&gt;
&lt;/gridSubset&gt;

--------- RESULT ---------
WMTS works, while WMS clients crashed. In Tomcat log directory I found:

tomcat7-stdout.log
22 Nov 14:42:23 (http-bio-8080-exec-356) ERROR [geowebcache.GeoWebCacheDispatcher] - null http://10.192.255.34:8082/geowebcache/service/wms

tomcat7-stderr.log
java.lang.NullPointerException
	at org.geowebcache.grid.GridSubset.getCoverageIntersection(GridSubset.java:243)
	at org.geowebcache.service.wms.WMSTileFuser.determineCanvasLayout(WMSTileFuser.java:228)
	at org.geowebcache.service.wms.WMSTileFuser.writeResponse(WMSTileFuser.java:450)
	at org.geowebcache.service.wms.WMSService.handleRequest(WMSService.java:260)
	at org.geowebcache.GeoWebCacheDispatcher.handleServiceRequest(GeoWebCacheDispatcher.java:344)
	at org.geowebcache.GeoWebCacheDispatcher.handleRequestInternal(GeoWebCacheDispatcher.java:254)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

On the other hand I can receive right WMS and WMTS capabilities:
wmts-getcapabilities
&lt;Layer&gt;
    &lt;ows:Title&gt;Oleata&lt;/ows:Title&gt;
    &lt;ows:Abstract&gt;Vizualizace DMU100 pro LMS.&lt;/ows:Abstract&gt;
    &lt;ows:Identifier&gt;oleata_dmu100&lt;/ows:Identifier&gt;
    &lt;Style isDefault="true"&gt;
      &lt;ows:Identifier&gt;default&lt;/ows:Identifier&gt;
    &lt;/Style&gt;
    &lt;Format&gt;image/png&lt;/Format&gt;
    &lt;TileMatrixSetLink&gt;      &lt;TileMatrixSet&gt;EPSG:3857&lt;/TileMatrixSet&gt;
      &lt;TileMatrixSetLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:11&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;682&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;709&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;1091&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;1133&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:12&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;1365&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;1419&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;2183&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;2266&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:13&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;2730&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;2838&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;4366&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;4532&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:14&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;5460&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;5677&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;8733&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;9064&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
        &lt;TileMatrixLimits&gt;
          &lt;TileMatrix&gt;EPSG:3857:15&lt;/TileMatrix&gt;
          &lt;MinTileRow&gt;10920&lt;/MinTileRow&gt;
          &lt;MaxTileRow&gt;11354&lt;/MaxTileRow&gt;
          &lt;MinTileCol&gt;17466&lt;/MinTileCol&gt;
          &lt;MaxTileCol&gt;18128&lt;/MaxTileCol&gt;
        &lt;/TileMatrixLimits&gt;
      &lt;/TileMatrixSetLimits&gt;
    &lt;/TileMatrixSetLink&gt;  &lt;/Layer&gt;

wms-getcapabilities.xml   ---- &lt;BoundingBox&gt; has right coors 
&lt;VendorSpecificCapabilities&gt;
	&lt;TileSet&gt;
	  &lt;SRS&gt;EPSG:3857&lt;/SRS&gt;
	  &lt;BoundingBox SRS="EPSG:3857" minx="1311047.9089648426" miny="6144314.080820311"  maxx="2152466.716210939"  maxy="6692214.699492186" /&gt;
	  &lt;Resolutions&gt;76.43702827453613 38.218514137268066 19.109257068634033 9.554628534317017 4.777314267158508 &lt;/Resolutions&gt;
	  &lt;Width&gt;256&lt;/Width&gt;
	  &lt;Height&gt;256&lt;/Height&gt;
	  &lt;Format&gt;image/png&lt;/Format&gt;
	  &lt;Layers&gt;oleata_dmu100&lt;/Layers&gt;
	  &lt;Styles&gt;&lt;/Styles&gt;
	&lt;/TileSet&gt;
&lt;/VendorSpecificCapabilities&gt;
&lt;Layer&gt;
	&lt;Title&gt;GeoWebCache WMS&lt;/Title&gt;
	&lt;Abstract&gt;Note that not all GeoWebCache instances provide a full WMS service.&lt;/Abstract&gt;
	&lt;LatLonBoundingBox minx="-180.0" miny="-90.0" maxx="180.0" maxy="90.0"/&gt;
	&lt;Layer&gt;
		&lt;Name&gt;oleata_dmu100&lt;/Name&gt;
		&lt;Title&gt;Oleata&lt;/Title&gt;
		&lt;Abstract&gt;Vizualizace DMU100 pro LMS.&lt;/Abstract&gt;
		&lt;SRS&gt;EPSG:3857&lt;/SRS&gt;
		&lt;BoundingBox SRS="EPSG:3857" minx="1311047.9089648426" miny="6144314.080820311" maxx="2152466.716210939" maxy="6692214.699492186"/&gt;
	&lt;/Layer&gt;
&lt;/Layer&gt;

**Comment by smithkm** [comment]
This is really more of a question for the users mailing list.  GitHub tickets are for specific bugs we've narrowed down enough to understand what needs to be fixed.
