### ISSUE TITLE
Support for WMS 1.3.0 still missing

### ISSUE THREAD

**Issue by mmzanger** [GeoWebCache/geowebcache#214]
The spec has been released some years ago and is still not supported by GWC.

**Comment by cpsTinK** [comment]
Any news in this issue yet?

**Comment by mmzanger** [comment]
Well, no! I don‘ t have any resources for funding available. Sorry! I will close or mute the issue….

Mit freundlichen Grüßen

Michael Zanger

SWM – Stadtwerke München
Informations- und Prozesstechnik
Anwendungen, Technische Geschäftsfelder
Telefon: +49 89 23 61-2575
Mobil:   +49 176 640 659 62
Telefax: +49 89 23 61-70 2575
zanger.michael@swm.de<mailto:zanger.michael@swm.de>
www.swm.de<http://www.swm.de/>
www.facebook.com/StadtwerkeMuenchen<http://www.facebook.com/StadtwerkeMuenchen>

SWM Services GmbH, Emmy-Noether-Straße 2, 80992 München; Geschäftsführer Dr. Florian Bieberbach, Herbert König, Stephan Schwarz, Erna-Maria Trixl, Werner Albrecht; Sitz München; Registergericht München HRB 126 674; Aufsichtsratsvorsitzender Oberbürgermeister Dieter Reiter

Diese E-Mail samt Anlagen ist vertraulich und nur für den genannten Empfänger bestimmt. Sollten Sie diese E-Mail-Nachricht versehentlich erhalten haben, so bitten wir Sie, hierüber den Absender zu informieren. Weiterhin ersuchen wir Sie, die E-Mail zu löschen. Es ist nicht zulässig, unbeabsichtigt erhaltene Informationen Dritten zu offenbaren, sie zu kopieren, weiterzuleiten oder in sonstiger Weise zu verwenden.

Von: Gureev Eugene [mailto:notifications@github.com]
Gesendet: Dienstag, 18. Oktober 2016 09:51
An: GeoWebCache/geowebcache
Cc: Zanger.Michael S-IP-AN-TG; Author
Betreff: Re: [GeoWebCache/geowebcache] Support for WMS 1.3.0 still missing (#214)


Any news in this issue yet?
