### ISSUE TITLE
Add pluggable in-memory caching for TileObjects

### ISSUE THREAD

**Issue by n-lagomarsini** [GeoWebCache/geowebcache#294]
It could be useful to configure a pluggable In-memory caching at blobstore level. This could be helpful in order to avoid persisting tiles on the disk and storing them in local memory or in a distributed environment.

**Comment by SwatiNEC** [comment]
Hi @n-lagomarsini @smithkm

I have a query regarding the two PR #295 and [geoserver#837](https://github.com/geoserver/geoserver/pull/837) mentioned above. I want to know which PR provides the functionality of in-memory caching(In Memory Blob Store).
Also please confirm the difference of GWC implementation in these two PRs.

**Comment by smithkm** [comment]
On April 29, 2020 3:39:41 a.m. PDT, Swati Jain <notifications@github.com> wrote:
>Hi @n-lagomarsini @smithkm
>
>I have a query regarding the two PR #295 and
>[geoserver#837](https://github.com/geoserver/geoserver/pull/837)
>mentioned above. I want to know which PR provides the functionality of
>in-memory caching(In Memory Blob Store).
>Also please confirm the difference of GWC implementation in these two
>PRs.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/GeoWebCache/geowebcache/issues/294#issuecomment-621120410

#295 adds the feature to GWC.  #837 provides a UI to control it in the instance of GWC embedded in GeoSever.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SwatiNEC** [comment]
Hi @smithkm 

Could you please tell me how can i configure "In memory blob store" in geoserver without UI control as I am using geoserver v2.7.0 which doesn't contains the implementation regarding [geoserver#837](https://github.com/geoserver/geoserver/pull/837).

**Comment by SwatiNEC** [comment]
Hi @n-lagomarsini @smithkm

Request you to please tell me how can i configure "In memory blob store" in geoserver without UI control as I am using geoserver v2.7.0 which doesn't contains the implementation regarding [geoserver#837](https://github.com/geoserver/geoserver/pull/837).

**Comment by smithkm** [comment]
@SwatiNEC Please do not use GitHub tickets or PRs to request support.  Use the community mailing list.

Instructions for setting up blob stores are included in the GeoWebCache documentation.  Also keep in mind that GWC 1.7 and GeoServer 2.7 are long past their end of life and are no longer supported by the community in any way.

Do not comment on this PR any further.
