### ISSUE TITLE
Empty GetFeatureInfo responses result in HTTP 400

### ISSUE THREAD

**Issue by hwbllmnn** [GeoWebCache/geowebcache#302]
If GetFeatureInfo is requested with INFO_FORMAT=text/html and the proxied service (tested with UMN Mapserver) returns a HTTP 200 with an empty document (Content-Length: 0), GWC responds with an HTTP 400 stating "All backends (1) failed. Last request: ...".

IMHO an empty GetFeatureInfo response with HTTP 200 should be passed through and not be considered an error.

**Comment by smithkm** [comment]
This could be a tricky behaviour to change without breaking downstream compatibility as the 0 length content is being used as part of some public extension points and  APIs to indicate that a a request hasn't been completed or needs to be retried.

**Comment by hwbllmnn** [comment]
Didn't realize this was still open, closing it now. Feel free to reopen if this is still a problem for anyone.
