### ISSUE TITLE
HazelcastCacheProviderTest fails without multicast support

### ISSUE THREAD

**Issue by bencaradocdavies** [GeoWebCache/geowebcache#306]
HazelcastCacheProviderTest fails if multicast is disabled or blocked by a firewall on the default interface of the host on which the test is run. I expect that it will also fail if UDP is blocked, or if there is no network.

Because multicast on Linux is disabled by default on loopback interfaces, Hazelcast ignores loopback interfaces when attempting multicast joining, so setting the network interface to loopback in the join configuration does not fix the test.

Workaround is to open the firewall (input) for multicast udp packets to 224.2.2.3:54327. For example, in `iptables`:

    -A INPUT -p udp -m pkttype --pkt-type multicast -s 192.168.1.1 -d 224.2.2.3 --dport 54327 -j ACCEPT

Note that `192.168.1.1` is the interface of the host on which the test is running. The `-s` option can be omitted.

A nicer test fixture could try joining first and quietly disable the test if the host lacks the network features to run the test. See GeoTools online tests for examples.

**Comment by aaime** [comment]
Or I guess we could have the test use TCP and 127.0.0.1 as the address for joining.

**Comment by bencaradocdavies** [comment]
TCP and 127.0.0.1 for joining should work. I only tried 127.0.0.1 for multicast (did not work, as discussed). What are we trying to test? Multicast node discovery needs an online test, but to test only tile put/delete, tcp on loopback will be fine.

**Comment by bencaradocdavies** [comment]
Here is a fix for master: https://github.com/GeoWebCache/geowebcache/pull/307

With tcp-ip joining on loopback as configured in this pull request, HazelcastCacheProviderTest passes with either (1) multicast blocked by a firewall, or (2) when non-loopback interfaces are down. Tested a full build as well.
