### ISSUE TITLE
Update for upstream integration of JAI-EXT and GeoTools

### ISSUE THREAD

**Issue by smithkm** [GeoWebCache/geowebcache#326]
An upstream change in GeoTools (https://github.com/geotools/geotools/pull/799) has broken the WMS module in `ImageEncoderImpl`

https://github.com/GeoWebCache/geowebcache/blob/master/geowebcache/wms/src/main/java/org/geowebcache/io/ImageEncoderImpl.java

**Comment by smithkm** [comment]
@n-lagomarsini since you made the upstream change and were the last one to touch `ImageEncoderImpl` you're probably in the best position to fix this.  Do you have time to take a look?

**Comment by n-lagomarsini** [comment]
Hi @smithkm,

I will fix the WMS module ASAP.

Regards,
Nicola.

**Comment by smithkm** [comment]
Build is working again, thanks @n-lagomarsini.
