### ISSUE TITLE
Can't seed any layer geowebcache 1.8

### ISSUE THREAD

**Issue by nqlong** [GeoWebCache/geowebcache#369]
I use geowebcache 1.8 to run seed. But the geoserver return this error: Althouh, geowebcache can make tile layer when I use gwc service. Thank for any help.

> 
> 2016-02-05 16:54:15,749 ERROR [geoserver.ows] - 
> org.geoserver.platform.ServiceException: Could not find layer usa:Lightning_Strikes
> 	at org.geoserver.wms.map.GetMapKvpRequestReader.parseLayers(GetMapKvpRequestReader.java:1252)
> 	at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:218)
> 	at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:80)
> 	at org.geoserver.ows.Dispatcher.parseRequestKVP(Dispatcher.java:1428)
> 	at org.geoserver.ows.Dispatcher.dispatch(Dispatcher.java:626)
> 	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:263)
> 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
> 	at org.geoserver.gwc.GWC.dispatchOwsRequest(GWC.java:1166)
> 	at org.geoserver.gwc.layer.GeoServerTileLayer.dispatchGetMap(GeoServerTileLayer.java:572)
> 	at org.geoserver.gwc.layer.GeoServerTileLayer.getMetatilingReponse(GeoServerTileLayer.java:517)
> 	at org.geoserver.gwc.layer.GeoServerTileLayer.seedTile(GeoServerTileLayer.java:711)
> 	at org.geowebcache.seed.SeedTask.doActionInternal(SeedTask.java:136)
> 	at org.geowebcache.seed.GWCTask.doAction(GWCTask.java:76)
> 	at org.geowebcache.seed.MTSeeder.call(MTSeeder.java:36)
> 	at org.geowebcache.seed.MTSeeder.call(MTSeeder.java:25)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)
> 2016-02-05 16:54:15,749 ERROR [seed.MTSeeder] - Problem communicating with GeoServer
> org.geowebcache.GeoWebCacheException: Problem communicating with GeoServer
> 	at org.geoserver.gwc.layer.GeoServerTileLayer.getMetatilingReponse(GeoServerTileLayer.java:522)
> 	at org.geoserver.gwc.layer.GeoServerTileLayer.seedTile(GeoServerTileLayer.java:711)
> 	at org.geowebcache.seed.SeedTask.doActionInternal(SeedTask.java:136)
> 	at org.geowebcache.seed.GWCTask.doAction(GWCTask.java:76)
> 	at org.geowebcache.seed.MTSeeder.call(MTSeeder.java:36)
> 	at org.geowebcache.seed.MTSeeder.call(MTSeeder.java:25)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.IllegalStateException: Expected: RenderedImageMap, got null
> 	at org.geoserver.gwc.layer.GeoServerTileLayer.dispatchGetMap(GeoServerTileLayer.java:575)
> 	at org.geoserver.gwc.layer.GeoServerTileLayer.getMetatilingReponse(GeoServerTileLayer.java:517)

**Comment by smithkm** [comment]
The bug ticketing system is for known bugs in need of fixing and feature requests.  If you are having a problem, please use the users mailing list.  Keep in mind that everyone there is a volunteer and responses will depend on other users having sufficient free time to deal with your question.  If it turns out it's a bug, you can make a bug report then with the details.
