### ISSUE TITLE
why only change the Y when calculating the topleft corner  of gridset

### ISSUE THREAD

**Issue by shevchenhe** [GeoWebCache/geowebcache#373]
when calculating the topleft corner in the **GridSet.java** file, i find the following code:

            double dTileHeight = getTileHeight();
            double dGridExtent = grid.getNumTilesHigh();

            double top = tileOrigin()[1] + dTileHeight * grid.getResolution() * dGridExtent;

            // Round off if we are within 0.5% of an integer value
            if (Math.abs(top - Math.round(top)) < (top / 200)) {
                top = Math.round(top);
            }

            leftTop[0] = tileOrigin()[0];
            leftTop[1] = top;

can anyone tell me why should calculate the y dynamically ?

**Comment by smithkm** [comment]
This would be better asked on the developers mailing list.  You should only file a bug ticket once it's clear that something needs to change.
