### ISSUE TITLE
TileLayer.getModifiableParameters() should not URLDecode strings from the input map

### ISSUE THREAD

**Issue by zeodtr** [GeoWebCache/geowebcache#377]
org.geowebcache.layer.TileLayer.getModifiableParameters() calls ServletUtils.selectedStringsFromMap() to select relevant parameter strings from the map.

But the problem is ServletUtils.selectedStringsFromMap() URLDecode()s the map values, while the map's values have been already decoded.

This makes it impossible to include '%' character to the map values.

**Comment by smithkm** [comment]
Duplicate of #193
