### ISSUE TITLE
MetaTile create tile operation should not perform a crop operation for BufferedImages

### ISSUE THREAD

**Issue by nmco** [GeoWebCache/geowebcache#383]
When creating a tile from a MetaTile we should avoid performing a crop operation if we are in the presence of a BufferedImage, we should instead rely on the subImage() method.

**Comment by smithkm** [comment]
This is not a very well stated ticket and appears to cover multiple issues which would be better handled as separate tickets.  That said I do appreciate that you made the effort to file a ticket rather than just dropping a pull request without any context.

**Comment by nmco** [comment]
You are correct, I add a better description and I will open another issue.
