### ISSUE TITLE
Question relating to ArcGIS compact caches

### ISSUE THREAD

**Issue by whgregory** [GeoWebCache/geowebcache#385]
The GeoWebCache documentation explicitly states that the ArcGIS compact cache format is not supported as it is not an open format. The release notes for GeoWebCache state that version 1.6.0-beta (2014-07-21) supports ArcGIS compact caches and version 1.8-beta (2015-08-28) supports ArcGIS 10.3 caches (which I interpret to be the second generation compact cache).

1) Am I correct in assuming this means that GeoWebCache will work with this data format, but as it is not an open format it is not 'officially' supported?
2) Is there anything different in terms of the configuration of the arcgisLayer tag when using this data format?

Regards,

**Comment by simboss** [comment]
I would move this discussion to the mailing list.
