### ISSUE TITLE
WMTS Capabilities document has invalid TileMatrixLimits

### ISSUE THREAD

**Issue by GatorScott** [GeoWebCache/geowebcache#411]
The capabilities document contains values for *TileRow and *TileColumn that cause validation to fail.  The elements *TileRow and *TileCol are defined as positiveInteger (1, 2, 3,...) in the XML Schema document despite the annotation that says "Minimum tile row index valid for this layer.  From 0 to maxTileRow".  It seems the proper type should be nonNegativeInteger, but that's an issue for the OGC.

**Comment by smithkm** [comment]
Yes this is a known issue #250 

It has already been reported to the OGC but they have not acted on it.
