### ISSUE TITLE
NIOLockProvider will not retry when failing to create output stream

### ISSUE THREAD

**Issue by emilzse** [GeoWebCache/geowebcache#427]
If NIOLockProvider fails to create output stream client gets empty tiles:

HTTP error code 400: "Failure while trying to get lock for key meta_{tile}.png"

GeoWebCache v1.9.1

```
currFos = new FileOutputStream(file);

try {
  currLock = currFos.getChannel().lock();
 } catch (OverlappingFileLockException e) {
    IOUtils.closeQuietly(currFos);
...
```

Moving `currFos = new FileOutputStream(file);` into the try would solve the issue.

**Comment by emilzse** [comment]
Patch solving issue:

[#427-Fixes-issue-with-output-stream-throwing-errors-patch.txt](https://github.com/GeoWebCache/geowebcache/files/461479/427-Fixes-issue-with-output-stream-throwing-errors-patch.txt)

**Comment by smithkm** [comment]
Hi @emilzse It would simplify the process of reviewing and merging your patches if you could use GitHub pull requests instead of patch files.

**Comment by emilzse** [comment]
Hi @smithkm 

Thank you for feedback.

Of cource i could do that, was just following the developer guidelines, maybe they need to be updated:
http://geowebcache.org/docs/current/development/index.html

**Comment by smithkm** [comment]
Ah I thought we had changed that.  Thanks.

**Comment by smithkm** [comment]
Updated the docs, it should be on the web site after we release 1.10-beta this weekend or early next week.  We will also be in feature freeze until RC1 after the beta release. As a bug fix this patch should be OK going in after the freeze.  

The performance patch may be a problem getting in during the freeze though.  It's probably also a more complicated review.  I'll try to find some time for a review but I can't make any promises.


https://github.com/GeoWebCache/geowebcache/commit/f9887ebd5dd15034e771e320079e2c4dc95a7c57

**Comment by smithkm** [comment]
You have a bunch of non-semantic formatting changes and no unit tests. Such formatting changes are generally discouraged as it makes the git history harder to follow.  If something is really messy, then formatting clean up is welcome, but it should go in a separate commit.

You also add some comments identifying yourself.  We rely on the git revision history for that instead so please don't include such comments.

**Comment by smithkm** [comment]
Switching to try-with-resources would also be a good idea.

**Comment by emilzse** [comment]
Thanks for feedback, I will try not to do auto format. But i did import the formatter that was part of source code. Could you verify that the formatter is still correct? 

I understand, how do you want me to proceed? Are you using the patches or should i redo the work and remove all comments and try to avoid the formatting? How far are you in a 1.9.2 version?

I guess the developer guidelines needs to be updated again removing:

> Please make sure you use Java 1.5 to compile to ensure that we do not introduce dependencies only available in 1.6.

**Comment by aaime** [comment]
Hi @emilzse, two quick notes:

- Formatting in the code has not always been respected, but we don't want changes mixing reformats and fixes as they make the review harder and the backports harder as well. So make sure that what you write is formatted correctly, but don't touch the rest (most IDE have an option to format on save only the modified lines)
- Releases are time boxed and 1.9.2 release is going out today based on a nightly CITE tests results reporting a specific commit that we'll tag from, so you're too late, but no worries, it's going to be included in the next 1.9.x release in December

**Comment by aaime** [comment]
Btw, the 1.9.2 release got delayed one day because we found a serious blocker bug, so we are going to make it tomorrow, that gives you a very tiny window to get the fix in (I would not get my hopes up, but it's something you can try, assuming @smithkm can review, merge and backport)

**Comment by smithkm** [comment]
@emilzse Yes that's some *very* old documentation that needs updating  Java 8 features are permitted in 1.10.x and 1.9.x.  The current maintenance branch, 1.8.x, is restricted to Java 7.  try-with-resources will be safe for all three.

I've been updating the dev guide in response to the out of date sections you've found.

I would have just applied the changes I suggested and merged, but I don't really have time to do the unit test.

**Comment by emilzse** [comment]
I want to try to commit my changes in the way you described above (no formatting etc) instead of creating patches and build it on the latest version.

Could i create my own branch since there are pretty big changes? Or should i commit to master?

From what should i create the Pull? (i am pretty new to git)

/ Emil

**Comment by smithkm** [comment]
Technically if you know you are just going to make one change and you aren't going to develop anything else until that change is merged into the community code base you could do your work on your own master branch.  This is a bad habit to get into though.
