### ISSUE TITLE
Writing 4-bit PNG with native JAI fails

### ISSUE THREAD

**Issue by dvntucker** [GeoWebCache/geowebcache#456]
In certain circumstances using PNG8 in GeoServer the resulting GetMap result can actually be optimized to 4-bit paletted PNG. Unfortunately the native JAI PNG writer can't encode anything other than 1, 8 or 16bit PNGs so the tile fails. GeoServer gets around this by checking the bit depth when native JAI is enabled and falling back to the pure Java encoder. 

I think we could do something similar with GWC. In ImageMime.getWriter we could check for non-supported bit depth and the native PNG writer (somehow) and either fallback to the pure Java PNGWriter manually, or just move on to the next writer found in the service registry (presumably the next one would be the pure Java version anyway).

**Comment by dvntucker** [comment]
GeoServer had a related ticket here:

https://osgeo-org.atlassian.net/browse/GEOT-4540

I don't think the linked PR was ever merged, but this case does appear to be handled in the PNGMapResponse

https://github.com/geoserver/geoserver/blob/master/src/wms/src/main/java/org/geoserver/wms/map/PNGMapResponse.java#L111

**Comment by smithkm** [comment]
https://github.com/GeoWebCache/geowebcache/pull/469
