### ISSUE TITLE
How to change the maximum "Number of tasks to use"?(tile-cache-seed)

### ISSUE THREAD

**Issue by asdawn** [GeoWebCache/geowebcache#496]
The default value is 16, which is a little small for me. How can I use 32 or 128 threads safely? Just modify the the selection list on the web page (HTML or Java), or change a lot of codes? Thanks.  

One small province cost 1 day (16 threads, on a quad-core machine) , that means it will cost months (about 60 days, I guess) to produce a full map of a country.  I want to make it faster, by using more threads (with two 32C64T servers), to finish it in 1 week. is it possible?

**Comment by smithkm** [comment]
Git hub tickets are for tracking identified bugs and features.  Please ask questions like this on the user's mailing list.
