### ISSUE TITLE
GeoWebCache pre-seed aerial imagery via WMTS as geo-referenced raster e.g. GeoTIFF/GeoJPEG2000

### ISSUE THREAD

**Issue by wulfgarpro** [GeoWebCache/geowebcache#499]
I have a large cache of JPEG files (700,000 tiles) that I've pre-seeded using a standalone GeoWebCache connected to a backing WMTS service.

I'd like to build a visual database with Terra Vista and it does not support OCG service endpoints, e.g. WMTS; It does however support GeoTIFF.

Before I extend the pre-seed function that GeoWebCache provides:

> Are there any existing tools or methods that will help me convert each JPEG in GeoWebCache's layered EPSG 4326 file cache into a geo-referenced raster format like GeoTIFF?

**Comment by smithkm** [comment]
The issue tracker is for bugs and features we want to fix or implement.  Support questions like this are best handled on the user mailing list.
