### ISSUE TITLE
Slashdot's mailing lists returning a 404

### ISSUE THREAD

**Issue by Jean-Roc** [GeoWebCache/geowebcache#503]
Hi,

I've been recently asked for help on geowebcache, I wanted to point the user to your slashdot's mailing-lists but it seems that both the [user](http://sourceforge.net/mailarchive/forum.php?forum_name=geowebcache-users) and [dev](http://sourceforge.net/mailarchive/forum.php?forum_name=geowebcache-devel) are returning _"Error 404 We're sorry but we weren't able to process this request"_.

These lists are those shown on geowebcache.org; if they are no longer the correct way to get in touch with the project, it would be better to reflect the change.

Regards,
Jean-Roc

**Comment by smithkm** [comment]
This may have been a temporary outage at Sourceforge.  The mailing list web interface seems to be working at the moment.  The mailing lists are still the primary means of communication for the project.
