### ISSUE TITLE
why arcgiscache layer GridsSet display as EPSG:4326_layerName

### ISSUE THREAD

**Issue by ailong** [GeoWebCache/geowebcache#504]
![tim 20170323204213](https://cloud.githubusercontent.com/assets/9276488/24248206/7f888412-1009-11e7-8d8b-1d614c451087.png)

**Comment by smithkm** [comment]
Hi Ailong,

The issue tracker is for identified bugs or feature requests.  Questions like this should be sent to the user mailing list.  If we figure out it is a bug, we will then create a ticket here.
