### ISSUE TITLE
WMS Dimension not properly translated to WMTS

### ISSUE THREAD

**Issue by GatorScott** [GeoWebCache/geowebcache#520]
WMTS capabilities document derived from WMS does not properly annotate the Identifier element of Dimension with ows, as in <ows:Identifier>FORECAST</ows:Identifier>.  This results in an invalid capabilities document.

**Comment by smithkm** [comment]
By "derived from" do you mean you are using the WMS auto configuration?  Could you describe the steps to replicate more clearly?

**Comment by bossie** [comment]
This is a duplicate of #679. :wink:
