### ISSUE TITLE
Demo pages failing to load OL static resources under /geowebcache context path 

### ISSUE THREAD

**Issue by mwengren** [GeoWebCache/geowebcache#541]
I've been working off of the master branch of GWC for some testing, and some commits in the past few weeks seem to have disabled the demo pages (the links to static resources are failing to include the /geowebcache path in their URLs, returning 404 errors).

For ex:
```
http://localhost:8090/geowebcache/demo/layer01?gridSet=EPSG:4326&format=image/png

Request URL:http://localhost:8090/openlayers3/ol.js
Request Method:GET
Status Code:404 Not Found
Remote Address:[::1]:8090
Referrer Policy:no-referrer-when-downgrade

Request URL:http://localhost:8090/openlayers3/ol.css
Request Method:GET
Status Code:404 Not Found
Remote Address:[::1]:8090
Referrer Policy:no-referrer-when-downgrade
```

I don't know the code too well, but I see a bunch of possibly related changes here:  https://github.com/GeoWebCache/geowebcache/commit/bb5ce18eecb5a7a027bd1807a7e629de298bb2e1.

Are there any tests that would find this?  `mvn clean install` worked for me, so I don't think it's a configuration/environment issue.

**Comment by smithkm** [comment]
Automated testing would require something like Selenium that can do tests in a browser.  We could add to the integration test a check that requesting the OL resources from a fixed location works but that was only part of the problem, it was also putting the wrong location in the HTML.

**Comment by mwengren** [comment]
@smithkm Thanks, that did it.  Appreciate the fix.  Will update Docker images when the next RC is released.  Maybe an automated test isn't necessary, but user testing comes in handy every once in a while!
