### ISSUE TITLE
Mass truncate layer misleading 500 response when nothing is cached

### ISSUE THREAD

**Issue by aaime** [GeoWebCache/geowebcache#587]
Issuing a mass truncate twice in a row against a layer that's not currently in use always results in a 500 error, Truncate failed.
How this works:
- The mass truncate delegates removal directly to the storage broker
- The default storage broke delegates it directly to the blob store
- The blob store interprets the layer name as a folder name or as a S3 bucket key (depending on the implementation) and removes it completely
- The second time this happens, the blob store remove(layer) call returns false, because the blob store cannot find the layer's folder/bucket entry

IMHO the code should verify if the layer exists (maybe at the storage broker layer or something) and return a 200 in case there is nothing on disk

**Comment by LiClark** [comment]
Many thanks for letting me know.
https://devgeoweb.neftex.com/Webmapper/#/webmapper/present/ for Thermal Temperature Gradient display looks ok now, the number formatted as 2 decimal as author expected.
Many thanks
