### ISSUE TITLE
Can't override default 4326 settings in 1.13-RC1

### ISSUE THREAD

**Issue by jonescc** [GeoWebCache/geowebcache#620]
In 1.11.4, we override the default set of resolutions for 4326 by redefining the default 4326 gridset in geowebcache.xml as follows:

 <gridSets>

    <gridSet>
      <name>EPSG:4326</name>
      <description>A default WGS84 tile matrix set where the first zoom level covers the world with two tiles
        on the horizonal axis and one tile over the vertical axis and each subsequent zoom level is calculated
        by half the resolution of its previous one.
      </description>
      <srs>
        <number>4326</number>
      </srs>
      <extent>
        <coords>
          <double>-180.0</double>
          <double>-90.0</double>
          <double>180.0</double>
          <double>90.0</double>
        </coords>
      </extent>
      <alignTopLeft>false</alignTopLeft>
      <resolutions>
        <double>1.40625</double>   
        <double>0.703125</double>
        <double>0.3515625</double>   
        <double>0.17578125</double>
        <double>0.087890625</double>
        <double>0.0439453125</double>
        <double>0.02197265625</double>
        <double>0.010986328125</double>
        <double>0.0054931640625</double>
        <double>0.00274658203125</double>
        <double>0.001373291015625</double>
        <double>6.866455078125E-4</double>
        <double>3.433227539062E-4</double>
        <double>1.716613769531E-4</double> 
      </resolutions>
      <metersPerUnit>111319.49079327358</metersPerUnit>
      <pixelSize>2.8E-4</pixelSize>

      <tileHeight>256</tileHeight>
      <tileWidth>256</tileWidth>

      <yCoordinateFirst>false</yCoordinateFirst>
    </gridSet>
  </gridSets>

Extract from 1.11.4 log where override definition is recognised and replaces default.

```
14 Mar 09:23:31 (RMI TCP Connection(2)-127.0.0.1) INFO [config.XMLFileResourceProvider] - Found configuration file in /home/craigj/tomcat7/apache-tomcat-7.0.70/temp/geowebcache
14 Mar 09:23:31 (RMI TCP Connection(2)-127.0.0.1) INFO [config.XMLConfiguration] - Configuration file validated fine.
14 Mar 09:23:31 (RMI TCP Connection(2)-127.0.0.1) INFO [config.GetCapabilitiesConfiguration] - Constructing from url http://geoserver-sandbox-geoserver.ap-southeast-2.elasticbeanstalk.com/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities
14 Mar 09:23:31 (RMI TCP Connection(2)-127.0.0.1) INFO [config.XMLConfiguration] - Initializing GridSets from /home/craigj/tomcat7/apache-tomcat-7.0.70/temp/geowebcache
14 Mar 09:23:31 (RMI TCP Connection(2)-127.0.0.1) INFO [config.XMLConfiguration] - Read GridSet EPSG:4326
14 Mar 09:23:31 (RMI TCP Connection(2)-127.0.0.1) WARN [grid.GridSetBroker] - Duplicate grid set EPSG:4326, removing previous instance, but it may still be referenced by layers.
14 Mar 09:23:31 (RMI TCP Connection(2)-127.0.0.1) INFO [config.XMLConfiguration] - Initializing layers from /home/craigj/tomcat7/apache-tomcat-7.0.70/temp/geowebcache
```

This no longer works in 1.13-beta/RC1 the override definition in geowebcache.xml appears to be ignored.  For example, the following request works fine in 1.11.4 but returns an error in 1.13-RC1

    http://localhost:8080/geowebcache/service/wms?service=WMS&request=GetMap&version=1.1.1&format=image/png&bbox=-180,-90,180,90&srs=EPSG:4326&width=256&height=256&STYLES=&layers=imos:argo_profile_map

    400: Requested horizontal resolution: 1.40625 , best match: 0.703125 exceeds 10% threshold. Perhaps the client is configured with an incorrect set of scales (resolutions), or the DPI setting is off compared to the one in GWC ?

We cache layers using a GetCapabilities statement rather than specifying individual layers (we have hundreds) and so we would prefer to be able to override the default 4326 settings.

Here's the wmts getcapabilities statements for the two versions:

[wmts-getcapabilities-1.11.4.txt](https://github.com/GeoWebCache/geowebcache/files/1808944/wmts-getcapabilities-1.11.4.txt)
[wmts-getcapabilities-1.13-RC1.txt](https://github.com/GeoWebCache/geowebcache/files/1808945/wmts-getcapabilities-1.13-RC1.txt)

Note that there are issues with the 4326 TileMatrixSets in the 1.13-RC1 version

**Comment by emerkle826** [comment]
This should be fixed on `master` now, as of https://github.com/GeoWebCache/geowebcache/pull/626
