### ISSUE TITLE
S3 Blob Store  - feature request - optionally support authenticating using IAM instance credentials

### ISSUE THREAD

**Issue by v-rfc** [GeoWebCache/geowebcache#632]
Use case: running geowebcache with S3 blob store backend on an AWS EC2 instance in an enterprise environment where it is not possible to obtain constant accessKey and secretKey values.

In this scenario, it would be preferable if the S3 blob store backend could obtain temporary AWS credentials to access S3 from IAM profile via EC2 instance metadata, and seamlessly renew these credentials when they expire.

It looks like the AWS Java SDK provides the machinery to do this. It may be a relatively straight forward change to enhance geowebcache to optionally obtain S3 credentials from an IAM profile via EC2 instance metadata instead of using fixed credentials written into a config file.

https://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/InstanceProfileCredentialsProvider.html

**Comment by jwb** [comment]
The ability to retrieve the credentials from the EC2 instance configuration is crucial to enabling a secure infrastructure.

**Comment by elee** [comment]
Pull Request open here: https://github.com/GeoWebCache/geowebcache/pull/660
