### ISSUE TITLE
WMTS operations URLs are invalid with AuthKey module 

### ISSUE THREAD

**Issue by ianturton** [GeoWebCache/geowebcache#640]
If the AuthKey module is in use it adds a parameter to the baseURL and then GeoWebCache adds a ? to the end of the URL when it should use & instead. 

The issue is in line 390 of /gwc-wmts/src/main/java/org/geowebcache/service/wmts/WMTSGetCapabilities.java

This is a follow up to [GEOS-8671](https://osgeo-org.atlassian.net/browse/GEOS-8671)

**Comment by jometho** [comment]
Hi @tbarsballe is this fix for available in Geoserver 2.13.1?

**Comment by tbarsballe** [comment]
Yes, it is; the associated PR was backported to GWC 1.13.x before the release.
