### ISSUE TITLE
Strange Performance for Reseeding a Heatmap 

### ISSUE THREAD

**Issue by huylaws** [GeoWebCache/geowebcache#651]
![heatmap-issue](https://user-images.githubusercontent.com/39217866/39957761-a6672238-562a-11e8-90c6-a42ca4dadb39.png)
I used geowebcache to tiling a heatmap. Since I had original data changed several times, I needed to reseed the heatmap again and agian. As the attached picture shows, I have some strange edges in my tiles after reseeding. 

I used a tomcat as a container holding GeoWebCache. I used to different ways to do reseeding. 
1. Click "Reseed" in GeoWebCache Rest page, the strange edges keep existence.
2. Remove tiles under directory of ${GeoWebCache_HOME}/{layer_name}, click "Seed" in GeoWebCache Rest page, the strange edges still exist.

In another side, I doubted whether it is a bug of OpenLayers. I used both original OpenLayers 3 and GeoWebCache's embedded OpenLayers, both didn't work. 

This problem really torqued me for quite a long time...

**Comment by smithkm** [comment]
This tracker is for bugs and feature requests, not support questions. Please use the user mailing list for that in future.  GeoServer rendering transformations generally aren't suitable for tile caching.  You might get it to work in this particular case using an appropriately sized gutter around the tiles.
