### ISSUE TITLE
can't access http://geowebcache.org/

### ISSUE THREAD

**Issue by yh371174229** [GeoWebCache/geowebcache#721]
http://geowebcache.org/ can't access.

**Comment by aaime** [comment]
https://www.geowebcache.org/

**Comment by GeoTob** [comment]
This is related to #719 -- https://geowebcache.org is linked to from google, from https://www.osgeo.org/projects/geowebcache/, from geoserver docs.

Can you implement a redirect from https://geowebcache.org to https://www.geowebcache.org perhaps?

**Comment by QingMings** [comment]
same issus. need access document page
