### ISSUE TITLE
TMS support

### ISSUE THREAD

**Issue by woowhoo** [GeoWebCache/geowebcache#735]
We are trying to cache map data from HERE Map Tile API - https://developer.here.com/documentation/map-tile/topics/quick-start-map-tile.html

Is Geowebcache compatible with HERE Map Tile API??

**Comment by smithkm** [comment]
Please ask questions on the user mailing list, the issue tracker is for known bugs and features.

GWC supports TMS.  I don't know anything about HERE though.
