### ISSUE TITLE
 can not @Autowired TileBreeder

### ISSUE THREAD

**Issue by ZChengL** [GeoWebCache/geowebcache#738]
why I can not @Autowired TileBreeder

**Comment by ZChengL** [comment]
curl -v -u admin:geoserver -XPOST -H "Content-type: text/xml" -d '<seedRequest><name>nurc:Arc_Sample</name><srs><number>4326</number></srs><zoomStart>1</zoomStart><zoomStop>12</zoomStop><format>image/png</format><type>truncate</type><threadCount>2</threadCount></seedRequest>'  "http://localhost:8080/geoserver/gwc/rest/seed/nurc:Arc_Sample.xml"

**Comment by smithkm** [comment]
If you want to incorporate GWC into another project as a library, please post a clear question to the users list describing what you are trying to do, how you are doing it, and the specific problems you've encountered.

If you are trying to do development you want to incorporate into the GWC codebase, please post to the development mailing list instead.

The issue tracker is for well defined bugs, features, or tasks not support questions.
