### ISSUE TITLE
Thread contention at equals and hashCode implementation of configuration objects

### ISSUE THREAD

**Issue by groldan** [GeoWebCache/geowebcache#796]
[GEOS-9385](https://osgeo-org.atlassian.net/browse/GEOS-9385) reveals usage of commons-lang3's  `EqualsBuilder` and `HashCodeBuilder` hinders concurrency and runtime performance when configuration objects are kept in collections.

`EqualsBuilder` and `HashcodeBuilder` impose severe concurrency penalties due to synchronization at the reflection code, that mostly chokes at    `java.lang.reflect.Field.declaredAnnotations()`.
    
Also, some config objects miss implementations of `equals()` and `hashCode()`.

**Comment by aaime** [comment]
I've looked at Lombok in the past with interest, but there is also a number of articles against in on the net:
* https://medium.com/@vgonzalo/dont-use-lombok-672418daa819
* https://artofcode.wordpress.com/2018/12/18/dont-use-lombok/
* https://github.com/jhipster/generator-jhipster/issues/398

As usual, before imposing a new library, it's best to discuss with the rest of the community.

**Comment by groldan** [comment]
Indeed we can do just as well without it. I'll patch it up.

**Comment by groldan** [comment]
Thanks Andrea, just replaced the use of lombok by eclipse generated versions.
Whether to adopt Lombok may be a worthy discussion but can take longer than needed. Looked at some of those links and I've my own opinion, some of them are old and everything is questionable. In any case, the discussion would span way beyond the needs of this fix, so let's have it on a separate thread if need be.
