### ISSUE TITLE
There is no support for creating maps in application/vnd.mapbox-vector-tile format

### ISSUE THREAD

**Issue by harry-wilson** [GeoWebCache/geowebcache#820]
We've developed a Geoserver (2.13.2) application which uses a standalone geowebcache (1.15.2) to create and serve vector tiles. The vector tile plugin is downloaded from official website and extracted in WEB_INF/lib folder and tile caching is enabled for a layer group to support vector tile as output. The wmsLayer part for this layer group is set in geowebcache.xml file as follow: 
```
<wmsLayer>
      <name>ws:VectorMVT</name>
      <mimeFormats>
        <string>image/png</string>
        <string>application/x-protobuf;type=mapbox-vector</string>
      </mimeFormats>
      <gridSubsets>
        <gridSubset>
          <gridSetName>EPSG:900913</gridSetName>
        </gridSubset>
        <gridSubset>
          <gridSetName>EPSG:4326</gridSetName>
        </gridSubset>
      </gridSubsets>
      <wmsUrl>
	<string>http://localhost:8080/geoserver/wms</string>
      </wmsUrl>
     <wmsLayers>ws:world_borders,ws:places_pnt</wmsLayers>
      <legends defaultWidth="20" defaultHeight="20" defaultFormat="application/x-protobuf;type=mapbox-vector">
        <legend style=""/>
      </legends>
    </wmsLayer>
```
The problem is serving the layer as PBF vector tiles in geowebcache web interface throws the following error but in PNG format it shows the map perfectly. Also using integrated Geowebcache tiles are served in pbf format in demo page which shows the vector tile plugin is work fine on Geoserver. 
```
MimeType mismatch, expected application/vnd.mapbox-vector-tile but got application/vnd.ogc.se_xml;charset=UTF-8 from http://localhost:8080/geoserver/wms?:
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://localhost:8080/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException code="InvalidFormat">
      There is no support for creating maps in application/vnd.mapbox-vector-tile format
</ServiceException></ServiceExceptionReport>

```

**Comment by aaime** [comment]
The versions of GeoServer and GWC are outdated, you should try a supported one, like 2.16.2 and 1.16.2 respectively. Also, the layer group should be pure vector. Works for me in that case, though to be honest, all it's happening inside the integrated GeoServer version, we don't use the stand alone much, if at all, where I work.

**Comment by Gaetanbrl** [comment]
Please, follow https://docs.geoserver.org/stable/en/user/extensions/vectortiles/tutorial.html. As @aaime said, yout version if a little bit oudated, but you can try with this tutorial.
